version: "3.9"

services:
  backend:
    build: ./moodly-social-api
    container_name: moodly-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build: ./moodly-social-web
    container_name: moodly-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
